# Production context
[build]
  publish = "dist"
  command = "vite build"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Don't apply this rule to robots.txt or sitemap.xml
  force = false
  conditions = {Path = {exclude = ["/robots.txt", "/sitemap.xml"]}}

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"